# Data Loading & Initial Validation

## Business Objective

Before analyzing the business, it is necessary to validate 
the integrity and quality of the source data.

The purpose of this notebook is to load all available 
datasets and perform an initial quality assessment.

## Notebook Objectives

- Load all available datasets
- Verify successful data loading
- Review table structure
- Assess data quality
- Identify potential issues
- Prepare data for the cleaning stage

## Import Libraries

The project uses the following libraries for data manipulation and file management.

In [15]:
import pandas as pd
import numpy as np

from pathlib import Path

## Load Source Data

All datasets are stored in the `06_Datasets/raw` directory.

The following step loads every available CSV file into memory.

In [16]:
DATA_PATH = Path("../06_Datasets/raw")

In [17]:
dataset_files = {
    "customers": "olist_customers_dataset.csv",
    "orders": "olist_orders_dataset.csv",
    "order_items": "olist_order_items_dataset.csv",
    "order_payments": "olist_order_payments_dataset.csv",
    "order_reviews": "olist_order_reviews_dataset.csv",
    "products": "olist_products_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "geolocation": "olist_geolocation_dataset.csv",
    "categories": "product_category_name_translation.csv"
}

In [22]:
datasets = {}
for name, filename in dataset_files.items():
    datasets[name] = pd.read_csv(DATA_PATH / filename)

## Dataset Overview

This section summarizes the dimensions of each dataset before detailed inspection.

In [19]:
overview = []

for name, df in datasets.items():
    overview.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Cols": df.shape[1],
        "Memory (mb)": round(df.memory_usage(deep=True).sum()/1024**2, 2)
    })

overview = pd.DataFrame(overview)
overview

          Dataset     Rows  Cols  Memory (mb)
0       customers    99441     5        26.59
1          orders    99441     8        52.94
2     order_items   112650     7        35.99
3  order_payments   103886     5        16.23
4   order_reviews    99224     7        39.12
5        products    32951     9         6.30
6         sellers     3095     4         0.59
7     geolocation  1000163     5       129.38
8      categories       71     2         0.01

The project consists of nine relational datasets.

The largest table is Order Items.

The smallest one is Category Translation.

The datasets represent different entities of an e-commerce platform.

## Data Structure Review

Each dataset is briefly inspected to understand its schema and business purpose.

In [25]:
for name, df in datasets.items():
    print("=" * 80)
    print(name.upper())
    print("=" * 80)
    display(df.head(3))
    display(df.dtypes.to_frame("Data Type"))
    print(f"Rows: {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]}")
    print(df.info())
    print("\n")

================================================================================
CUSTOMERS
================================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP

                         Data Type
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object

Rows: 99,441
Columns: 5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None


================================================================================
ORDERS
================================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

                              Data Type
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object

Rows: 99,441
Columns: 8
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None


================================================================================
ORDER_ITEMS
================================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

                    Data Type
order_id               object
order_item_id           int64
product_id             object
seller_id              object
shipping_limit_date    object
price                 float64
freight_value         float64

Rows: 112,650
Columns: 7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None


================================================================================
ORDER_PAYMENTS
================================================================================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71

                     Data Type
order_id                object
payment_sequential       int64
payment_type            object
payment_installments     int64
payment_value          float64

Rows: 103,886
Columns: 5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None


================================================================================
ORDER_REVIEWS
================================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24

                        Data Type
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object

Rows: 99,224
Columns: 7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB
None


================================================================================
PRODUCTS
================================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0

                           Data Type
product_id                    object
product_category_name         object
product_name_lenght          float64
product_description_lenght   float64
product_photos_qty           float64
product_weight_g             float64
product_length_cm            float64
product_height_cm            float64
product_width_cm             float64

Rows: 32,951
Columns: 9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None


================================================================================
SELLERS
================================================================================

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ

                       Data Type
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object

Rows: 3,095
Columns: 4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB
None


================================================================================
GEOLOCATION
================================================================================

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP

                            Data Type
geolocation_zip_code_prefix     int64
geolocation_lat               float64
geolocation_lng               float64
geolocation_city               object
geolocation_state              object

Rows: 1,000,163
Columns: 5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB
None


================================================================================
CATEGORIES
================================================================================

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

                              Data Type
product_category_name            object
product_category_name_english    object

Rows: 71
Columns: 2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB
None

## Data Quality Assessment

The following checks evaluate the overall quality of the source data.

In [35]:
quality_report = []

for name, df in datasets.items():
    quality_report.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Cols": df.shape[1],
        "Missing values": df.isna().sum().sum(),
        "Missing %": ((df.isna().sum().sum() / (df.shape[0] * df.shape[1])) * 100).round(2),
        "Duplicate Rows": df.duplicated().sum(),
        "Duplicates %": ((df.duplicated().sum() / df.shape[0]) * 100).round(2),
    })

quality_report = pd.DataFrame(quality_report)
quality_report

,Dataset,Rows,Cols,Missing values,Missing %,Duplicate Rows,Duplicates %
0,customers,99441,5,0,0.00,0,0.00
1,orders,99441,8,4908,0.62,0,0.00
2,order_items,112650,7,0,0.00,0,0.00
3,order_payments,103886,5,0,0.00,0,0.00
4,order_reviews,99224,7,145903,21.01,0,0.00
5,products,32951,9,2448,0.83,0,0.00
6,sellers,3095,4,0,0.00,0,0.00
7,geolocation,1000163,5,0,0.00,261831,26.18
8,categories,71,2,0,0.00,0,0.00

## Initial Findings

The initial assessment indicates that:

- All datasets were successfully loaded.
- Dataset dimensions match the expected structure.
- Some tables contain missing values that require further investigation.
- Duplicate rows are minimal or absent.
- Several columns require datatype conversion.
- The data appears suitable for preprocessing.

## Next Steps

The next stage focuses on data cleaning and preprocessing.

Tasks include:

- handling missing values;
- validating primary keys;
- converting data types;
- checking business consistency;
- preparing analytical datasets.